testar forma diferente de passar valor para yq

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -56,11 +56,9 @@ jobs:
       
       - name: Replace ECR image string value
         env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
-          IMAGE_TAG: latest
+          IMAGE_PATH: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest
         run: |
-          yq e '.spec.template.spec.containers[0].image = "$ECR_REGISTRY + "/" + $ECR_REPOSITORY + ":" + $IMAGE_TAG"' -i src/infra/eks/api/02-snack-tech-api-deployment.yaml || { echo "Error updating ecr_image_url_repo_tag value"; exit 1; }
+          yq e '.spec.template.spec.containers[0].image = "'"$IMAGE_PATH"'"' -i src/infra/eks/api/02-snack-tech-api-deployment.yaml || { echo "Error updating ecr_image_url_repo_tag value"; exit 1; }
       - name: Deploy to EKS
         run: |
           kubectl apply -f src/infra/eks/api
