ajustar variaveis e diretorio de execução do build do container

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,8 +34,8 @@ jobs:
           ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
           IMAGE_TAG: latest
         run: |
-          docker build -t env.ECR_REGISTRY/env.ECR_REPOSITORY:env.IMAGE_TAG .
-          docker push env.ECR_REGISTRY/env.ECR_REPOSITORY:env.IMAGE_TAG
+          docker build -f infra.web-api/SnackTech.Driver.API/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG src
+          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
       # Install Kubectl (generic installation method)
       - name: Install Kubectl
@@ -52,7 +52,7 @@ jobs:
         env:
           MSSQL_CONNECTION_STRING: ${{ secrets.K8S_DB_CONNECTION_STRING }}
         run: |
-          yq e '.data["msslq-connection-string"] = env.MSSQL_CONNECTION_STRING' -i infra/eks/api/01-snack-tech-api-secret.yml || { echo "Error updating msslq-connection-string value"; exit 1; }
+          yq e '.data["msslq-connection-string"] = $MSSQL_CONNECTION_STRING' -i infra/eks/api/01-snack-tech-api-secret.yml || { echo "Error updating msslq-connection-string value"; exit 1; }
       
       - name: Replace ECR image string value
         env:
@@ -60,7 +60,7 @@ jobs:
           ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
           IMAGE_TAG: latest
         run: |
-          yq e '.spec.template.spec.containers[0].image = env.ECR_REGISTRY + "/" + env.ECR_REPOSITORY + ":" + env.IMAGE_TAG' -i infra/eks/api/02-snack-tech-api-deployment.yml || { echo "Error updating ecr_image_url_repo_tag value"; exit 1; }
+          yq e '.spec.template.spec.containers[0].image = $ECR_REGISTRY + "/" + $ECR_REPOSITORY + ":" + $IMAGE_TAG' -i infra/eks/api/02-snack-tech-api-deployment.yml || { echo "Error updating ecr_image_url_repo_tag value"; exit 1; }
 
       - name: Deploy to EKS
         run: |
